# Generated by Django 4.2.20 on 2025-11-24 16:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import opaque_keys.edx.django.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIWorkflowSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('course_id', opaque_keys.edx.django.models.CourseKeyField(blank=True, help_text='Course associated with this session', max_length=255, null=True)),
                ('location_id', opaque_keys.edx.django.models.UsageKeyField(blank=True, help_text='Location associated with this session', max_length=255, null=True)),
                ('local_submission_id', models.CharField(blank=True, help_text='ID of the submission associated with this session', max_length=255, null=True)),
                ('remote_response_id', models.CharField(blank=True, help_text='ID of the last response sent to the user', max_length=255, null=True)),
                ('metadata', models.JSONField(default=dict, help_text='Additional session metadata')),
                ('user', models.ForeignKey(help_text='User associated with this session', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
