# Generated by Django 4.2.20 on 2025-12-04 20:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import opaque_keys.edx.django.models
import openedx_ai_extensions.workflows.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('openedx_ai_extensions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIWorkflowConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', opaque_keys.edx.django.models.CourseKeyField(blank=True, help_text='Course associated with this session', max_length=255, null=True)),
                ('location_regex', models.CharField(blank=True, default=None, help_text='Location regex this config applies to', max_length=255, null=True)),
                ('orchestrator_class', models.CharField(help_text='Full class name of the orchestrator', max_length=255, validators=[openedx_ai_extensions.workflows.models.validate_orchestrator_class])),
                ('processor_config', models.JSONField(default=dict, help_text='LLM provider, model, template settings', validators=[openedx_ai_extensions.workflows.models.validate_processor_config])),
                ('actuator_config', models.JSONField(default=dict, help_text='Response formatting and UI settings')),
                ('service_variant', models.CharField(choices=[('lms', 'LMS'), ('cms', 'CMS')], default='lms', help_text='Service variant to use for this workflow', max_length=50)),
                ('enabled', models.BooleanField(default=True, help_text='Whether this workflow configuration is enabled')),
            ],
            options={
                'indexes': [models.Index(fields=['course_id', 'location_regex', 'service_variant'], name='openedx_ai__course__ad3ca4_idx')],
                'unique_together': {('course_id', 'location_regex', 'service_variant')},
            },
        ),
    ]
