# Generated by Django 4.2.20 on 2025-12-19 20:38

from django.db import migrations, models
import django.db.models.deletion
import opaque_keys.edx.django.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('openedx_ai_extensions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIWorkflowProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(help_text='Human readable identifier for the AI workflow profile (lowercase, hyphens allowed). Used for analytics.', max_length=255, unique=True)),
                ('description', models.TextField(blank=True, help_text='Description of the AI workflow profile', null=True)),
                ('base_filepath', models.CharField(help_text="Relative path to base template file (e.g., 'educator_assistant/quiz_generator.json')", max_length=1024)),
                ('content_patch', models.JSONField(blank=True, default=dict, help_text='JSON Merge Patch (RFC 7386) to apply to base template')),
            ],
            options={
                'verbose_name': 'AI Workflow Profile',
                'verbose_name_plural': 'AI Workflow Profiles',
            },
        ),
    ]
