# Generated by Django 4.2.20 on 2025-12-19 21:13

from django.db import migrations, models
import django.db.models.deletion
import opaque_keys.edx.django.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('openedx_ai_extensions', '0002_aiworkflowprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aiworkflowprofile',
            name='content_patch',
            field=models.TextField(blank=True, default='', help_text='JSON5 Merge Patch (RFC 7386) to apply to base template. Supports comments and trailing commas.'),
        ),
    ]
