# Generated by Django 4.2.20 on 2025-12-19 21:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import opaque_keys.edx.django.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('openedx_ai_extensions', '0003_aiworkflowprofile_patch'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiworkflowsession',
            name='profile',
            field=models.ForeignKey(default=None, help_text='AI workflow profile associated with this session', on_delete=django.db.models.deletion.CASCADE, to='openedx_ai_extensions.aiworkflowprofile'),
        ),
        migrations.CreateModel(
            name='AIWorkflowScope',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('location_regex', models.CharField(blank=True, help_text='Regex pattern to match location IDs for this configuration', max_length=255, null=True)),
                ('course_id', opaque_keys.edx.django.models.CourseKeyField(blank=True, help_text='Course associated with this session', max_length=255, null=True)),
                ('service_variant', models.CharField(choices=[('lms', 'LMS'), ('cms', 'CMS - Studio')], default='lms', help_text='Service variant where this workflow applies', max_length=10)),
                ('enabled', models.BooleanField(default=True, help_text='Indicates if this workflow configuration is enabled')),
                ('profile', models.ForeignKey(help_text='AI workflow profile associated with this configuration', on_delete=django.db.models.deletion.CASCADE, to='openedx_ai_extensions.aiworkflowprofile')),
            ],
        ),
        migrations.AddField(
            model_name='aiworkflowsession',
            name='scope',
            field=models.ForeignKey(default=None, help_text='AI workflow scope associated with this session', on_delete=django.db.models.deletion.CASCADE, to='openedx_ai_extensions.aiworkflowscope'),
        ),
        migrations.AlterUniqueTogether(
            name='aiworkflowsession',
            unique_together={('user', 'scope', 'profile')},
        ),
    ]
