# Generated by Django 4.2.17 on 2026-02-11 14:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('openedx_ai_extensions', '0005_prompttemplate'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aiworkflowprofile',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='aiworkflowsession',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='aiworkflowsession',
            name='profile',
            field=models.ForeignKey(help_text='AI workflow profile associated with this session', on_delete=django.db.models.deletion.CASCADE, to='openedx_ai_extensions.aiworkflowprofile'),
        ),
        migrations.AlterField(
            model_name='aiworkflowsession',
            name='scope',
            field=models.ForeignKey(help_text='AI workflow scope associated with this session', on_delete=django.db.models.deletion.CASCADE, to='openedx_ai_extensions.aiworkflowscope'),
        ),
        migrations.AlterUniqueTogether(
            name='aiworkflowsession',
            unique_together={('user', 'scope', 'profile', 'course_id', 'location_id')},
        ),
    ]
