# Generated by Django 4.2.20 on 2026-02-21 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openedx_ai_extensions', '0006_alter_aiworkflowprofile_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiworkflowscope',
            name='priority',
            field=models.IntegerField(default=0, help_text='Resolution priority when multiple scopes match the same location_regex and ui_slot_selector_id. Higher value wins. Scopes with equal priority and equal matches raise an error.'),
        ),
        migrations.AddField(
            model_name='aiworkflowscope',
            name='ui_slot_selector_id',
            field=models.CharField(blank=True, db_index=True, help_text='Identifier of the UI slot that renders this scope. Required when multiple scopes share the same location. Must match the uiSlotSelectorId prop passed by the frontend widget.', max_length=255, null=True),
        ),
    ]
