# Generated by Django 4.2.20 on 2026-03-03 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openedx_ai_extensions', '0006_alter_aiworkflowprofile_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiworkflowscope',
            name='specificity_index',
            field=models.IntegerField(default=0, editable=False, help_text='Auto-calculated resolution specificity (populated on save). Weighted sum of non-null discriminator fields: location_regex (+4) + course_id (+2) + ui_slot_selector_id (+1). Higher value means more specific and wins in resolution order.'),
        ),
        migrations.AddField(
            model_name='aiworkflowscope',
            name='ui_slot_selector_id',
            field=models.CharField(db_index=True, default='', help_text='Identifier of the UI slot that renders this scope. Must exactly match the uiSlotSelectorId prop sent by the frontend widget. The scope only renders when a widget sends this exact value. Choose from the available options configured in OPENEDX_AI_EXTENSIONS_UI_SLOT_IDS.', max_length=255),
        ),
    ]
