# Generated by Django 4.2.20 on 2026-02-27 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openedx_ai_extensions', '0006_alter_aiworkflowprofile_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiworkflowscope',
            name='specificity_index',
            field=models.IntegerField(default=0, editable=False, help_text='Auto-calculated resolution specificity. Computed as the sum of non-null discriminator fields: course_id (1) + ui_slot_selector_id (1) + location_regex (1). Higher value means more specific. Populated automatically on save.'),
        ),
        migrations.AddField(
            model_name='aiworkflowscope',
            name='ui_slot_selector_id',
            field=models.CharField(blank=True, db_index=True, help_text='Identifier of the UI slot that renders this scope. Required when multiple scopes share the same location. Must match the uiSlotSelectorId prop passed by the frontend widget.', max_length=255, null=True),
        ),
    ]
