import { useState } from "react";
import { useIntl } from '@edx/frontend-platform/i18n';
import { Alert, Button, Container, Form, FullscreenModal, Stack, Stepper } from "@openedx/paragon";
import QuestionCard from './QuestionCard';
import messages from '../messages';
import { useLibraryCreatorContext } from '../context/LibraryCreatorContext';

const EditModal = () => {
  const {
    questions,
    errorMessage,
    collectionName,
    setCollectionName,
    libraries,
    selectedLibrary,
    libraryError,
    isLoadingLibraries,
    setSelectedLibrary,
    setLibraryError,
    handleSave,
    handleStartOver,
    activeCount,
    isOpen,
    close,
  } = useLibraryCreatorContext();
  const intl = useIntl();
  const steps = ['review-questions', 'save-questions'];
  const [currentStep, setCurrentStep] = useState(steps[0]);
  return (
    <>
      <Stepper activeKey={currentStep}>
        <FullscreenModal
          title="AI Generated Problem Editor"
          className="bg-light-200"
          isOpen={isOpen}
          onClose={close}
          beforeBodyNode={<Stepper.Header className="border-bottom border-light" />}
          footerNode={(
            <>
              <Stepper.ActionRow eventKey="review-questions">
                <Stepper.ActionRow.Spacer />
                <Button onClick={() => setCurrentStep('save-questions')}>Next</Button>
              </Stepper.ActionRow>

              <Stepper.ActionRow eventKey="save-questions">
                <Button variant="outline-primary" onClick={() => setCurrentStep('review-questions')}>
                  Previous
                </Button>
                <Stepper.ActionRow.Spacer />
                <Button onClick={close}>Apply</Button>
              </Stepper.ActionRow>
            </>
          )}
        >
          <Container size="md">

            <Stepper.Step eventKey="review-questions" title="Review the AI generated problems">
              <h2>Review the problems generated by by the AI</h2>
              <p>You can edit manually the generated question or add feedback and let the AI apply changes for you.</p>
              <p className="small font-weight-bold mb-2">
                {intl.formatMessage(messages['ai.library.creator.review.heading'], { count: questions.length, })}
              </p>
              {errorMessage && (<Alert variant="danger" dismissible onClose={() => { }}>
                {errorMessage}
              </Alert>)
              }
              <div className="question-list mb-3">
                {questions.map((q, i) => (
                  <QuestionCard key={`${q.displayName}-${i}`} index={i} />
                ))}
              </div>
            </Stepper.Step>

            <Stepper.Step eventKey="save-questions" title="Save the problems in library">
              <h2>Save in library</h2>
              {/* Collection name */}
              <Form.Group controlId="collectionName" className="mb-2">
                <Form.Label className="small font-weight-bold">
                  {intl.formatMessage(messages['ai.library.creator.collection.name.label'])}
                </Form.Label>
                <Form.Control
                  type="text"
                  value={collectionName}
                  onChange={(e) => setCollectionName(e.target.value)}
                  size="sm"
                  placeholder={intl.formatMessage(messages['ai.library.creator.collection.name.placeholder'])}
                />
              </Form.Group>

              {/* Library picker */}
              <Form.Group controlId="librarySelect" className="mb-2">
                <Form.Label className="small font-weight-bold">
                  {intl.formatMessage(messages['ai.library.creator.library.label'])}
                  <span className="text-danger">*</span>
                </Form.Label>
                <Form.Control as="select" value={selectedLibrary}
                  onChange={(e) => { setSelectedLibrary(e.target.value); setLibraryError(''); }}
                  disabled={isLoadingLibraries} size="sm"              >
                  <option value="">                  {
                    isLoadingLibraries ? intl.formatMessage(messages['ai.library.creator.library.loading'])
                      : intl.formatMessage(messages['ai.library.creator.library.placeholder'])}
                  </option>
                  {libraries.map((lib) => (<option key={lib.id} value={lib.id}>
                    {`${lib.id} — ${lib.title}`}
                  </option>))}
                  {!isLoadingLibraries && libraries.length === 0 && (<option disabled>
                    {intl.formatMessage(messages['ai.library.creator.library.none'])}
                  </option>)}
                </Form.Control>
              </Form.Group>
              {libraryError &&
                (<Alert variant="danger" className="mb-2" dismissible onClose={() => setLibraryError('')}>
                  {libraryError}              </Alert>)}
              <Stack gap={2}>
                <Button variant="primary" size="sm" className="w-100"
                  disabled={!selectedLibrary || activeCount === 0}
                  onClick={handleSave}
                >
                  {intl.formatMessage(messages['ai.library.creator.save.button'])}
                </Button>
                <Button variant="outline-secondary" size="sm" className="w-100" onClick={handleStartOver}
                >
                  {intl.formatMessage(messages['ai.library.creator.start.over'])}
                </Button>
              </Stack>
            </Stepper.Step>
          </Container>
        </FullscreenModal>
      </Stepper>
    </>
  )
}

export default EditModal;
