name: Integration Tests

on:
  push:
    branches:
      - main

  workflow_dispatch:
    inputs:
      sha:
        required: false
        type: string

      ref:
        required: false
        type: string

      repository:
        required: false
        type: string

jobs:
  integration:
    name: Live LLM Integration Tests

    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./backend

    steps:
      - name: Checkout PR commit
        if: inputs.sha != ''
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5  #v4.3.1
        with:
          repository: ${{ inputs.repository }}
          ref: ${{ inputs.sha }}

      - name: Checkout repository
        if: inputs.sha == ''
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5  #v4.3.1

      - name: Set up Python
        uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5.6.0
        with:
          python-version: "3.12"

      - name: Install Dependencies
        run: |
          pip install -r requirements/test.txt
          pip install -e .

      - name: Run integration tests
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
        run: make test-integration
