name: Release
on:
  pull_request:
    types:
      - closed
    branches:
      - main

jobs:
  release:
    if: github.event.pull_request.merged == true && startsWith(github.head_ref, 'bot/v')
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6
      - name: Create tag
        id: tag_version
        uses: python-semantic-release/python-semantic-release@350c48fcb3ffcdfd2e0a235206bc2ecea6b69df0 # v10.5.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          push: false
      - name: Create a GitHub release
        if: steps.tag_version.outputs.tag
        uses: ncipollo/release-action@339a81892b84b4eeb0f6e744e4574d79d0d9b8dd # v1.21.0
        with:
          tag: ${{ steps.tag_version.outputs.tag }}
          name: Release ${{ steps.tag_version.outputs.tag }}
          body: ${{ steps.tag_version.outputs.release_notes }}
